### PR TITLE
made overflow: hidden to have no scroll bars in chrome

### PR DESCRIPTION
**Pull request by BorntraegerMarc**

### CODE REVIEW

**Comment by firstor** [comment]
Also please merge remote branch `master` into the PR.

**Comment by BorntraegerMarc** [comment]
@firstor you mean my `master` branch in BorntraegerMarc/hirst-dialog? Why should I do that? There is nothing in my master branch...

**Comment by firstor** [comment]
I just configured Travis build on remote `master` so you should probably merge it into your PR to make CI build working on your PR 😄

**Comment by BorntraegerMarc** [comment]
ah got it 😄 But that is going to be kind of a problem... I can't merge the remote to forked branches. Github doesn't allow it :/ maybe you can copy that one line yourself & test it out in one of your branches?

**Comment by firstor** [comment]
@BorntraegerMarc I don't have any time to teach you right now 😜  
You may want probably to configure two origins in your local repo (`git remote add ...`) ~ one might be `origin` for your remote repo (forked repo) and another one might be `upstream` for this main repo. So you may want to 
* pull `master` from `upstream` into your local `master`
* merge your local `master` into your working branch 
* then push your branch to your remote repo (`origin`) in order to update your PR

Don't ask anymore!

**Pull request closed without merging**
